"""empty message

Revision ID: 14f8aeca71f0
Revises: 67374ee5039b
Create Date: 2023-04-14 18:31:54.940332

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '14f8aeca71f0'
down_revision = '67374ee5039b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('daily_attendances', schema=None) as batch_op:
        batch_op.alter_column('late_approval_status',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('daily_attendances', schema=None) as batch_op:
        batch_op.alter_column('late_approval_status',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
