"""empty message

Revision ID: 61ee689bfbff
Revises: c76c1a1d494e
Create Date: 2023-04-29 17:09:14.700618

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '61ee689bfbff'
down_revision = 'c76c1a1d494e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_image', sa.String(length=80), nullable=True))
        batch_op.create_unique_constraint(None, ['user_image'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('user_image')

    # ### end Alembic commands ###
