"""empty message

Revision ID: 67374ee5039b
Revises: 6b3af2aa575a
Create Date: 2023-04-14 18:04:18.973448

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '67374ee5039b'
down_revision = '6b3af2aa575a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('daily_attendances',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.String(length=10), nullable=False),
    sa.Column('office_entry_time', sa.String(length=10), nullable=False),
    sa.Column('office_exit_time', sa.String(length=10), nullable=False),
    sa.Column('late_status', sa.Integer(), nullable=True),
    sa.Column('late_cause', sa.String(length=100), nullable=True),
    sa.Column('late_approval_status', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('daily_attendaces')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('daily_attendaces',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('date', sa.VARCHAR(length=10), nullable=False),
    sa.Column('office_entry_time', sa.VARCHAR(length=10), nullable=False),
    sa.Column('late_status', sa.INTEGER(), nullable=True),
    sa.Column('late_cause', sa.VARCHAR(length=100), nullable=True),
    sa.Column('late_approval_status', sa.INTEGER(), nullable=False),
    sa.Column('employee_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('daily_attendances')
    # ### end Alembic commands ###
