"""empty message

Revision ID: 6b3af2aa575a
Revises: 941999187320
Create Date: 2023-04-14 16:08:42.261744

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6b3af2aa575a'
down_revision = '941999187320'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('daily_attendaces',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.String(length=10), nullable=False),
    sa.Column('office_entry_time', sa.String(length=10), nullable=False),
    sa.Column('late_status', sa.Integer(), nullable=True),
    sa.Column('late_cause', sa.String(length=100), nullable=True),
    sa.Column('late_approval_status', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('daily_attendaces')
    # ### end Alembic commands ###
