"""empty message

Revision ID: 941999187320
Revises: 4d070869bb54
Create Date: 2023-04-07 00:03:29.603373

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '941999187320'
down_revision = '4d070869bb54'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('leave_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('leaves',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('leave_type_id', sa.Integer(), nullable=False),
    sa.Column('leave_start_date', sa.String(length=10), nullable=False),
    sa.Column('leave_end_date', sa.String(length=10), nullable=False),
    sa.Column('leave_approval_status', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['leave_type_id'], ['leave_types.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('leaves')
    op.drop_table('leave_types')
    # ### end Alembic commands ###
