"""empty message

Revision ID: e84030157c4a
Revises: 14f8aeca71f0
Create Date: 2023-04-14 22:03:15.258194

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e84030157c4a'
down_revision = '14f8aeca71f0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('daily_attendances', schema=None) as batch_op:
        batch_op.add_column(sa.Column('day', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('month', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('year', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('daily_attendances', schema=None) as batch_op:
        batch_op.drop_column('year')
        batch_op.drop_column('month')
        batch_op.drop_column('day')

    # ### end Alembic commands ###
