from models.religion import ReligionModel
from models.marital_status import MaritalStatusModel
from models.employee import EmployeeModel
from models.department import DepartmentModel
from models.office_post import OfficePostModel
from models.office import OfficeModel
from models.leave import LeaveModel
from models.leave_type import LeaveTypeModel
from models.daily_attendance import DailyAttendanceModel
